export enum UserRole {
  GUEST = 'GUEST',
  MEMBER = 'MEMBER',
  VERIFIED_MEMBER = 'VERIFIED_MEMBER',
  PASTOR_VERIFIER = 'PASTOR_VERIFIER',
  ADMIN = 'ADMIN',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum MaritalStatus {
  NEVER_MARRIED = 'NEVER_MARRIED',
  WIDOWED = 'WIDOWED',
  DIVORCED_ANNULLED = 'DIVORCED_ANNULLED',
}

export enum BaptismStatus {
  BAPTIZED_SDA = 'BAPTIZED_SDA',
  PLANNING_BAPTISM = 'PLANNING_BAPTISM',
  ATTENDING_NON_MEMBER = 'ATTENDING_NON_MEMBER',
}

export enum SabbathObservance {
  STRICT_SUNSET_TO_SUNSET = 'STRICT_SUNSET_TO_SUNSET',
  MODERATE = 'MODERATE',
  LEARNING = 'LEARNING',
}

export enum DietType {
  STRICT_VEGAN = 'STRICT_VEGAN',
  LACTO_OVO_VEGETARIAN = 'LACTO_OVO_VEGETARIAN',
  PESCATARIAN = 'PESCATARIAN',
  NON_VEGETARIAN_CLEAN_ONLY = 'NON_VEGETARIAN_CLEAN_ONLY',
}

export enum AlcoholTobaccoStance {
  STRICT_ABSTINENCE = 'STRICT_ABSTINENCE',
  NEVER_USED = 'NEVER_USED',
  OCCASIONAL = 'OCCASIONAL',
  PAST_USE_QUIT = 'PAST_USE_QUIT',
}

export enum MinistryInvolvement {
  PATHFINDERS = 'PATHFINDERS',
  ADVENTURERS = 'ADVENTURERS',
  SABBATH_SCHOOL = 'SABBATH_SCHOOL',
  AY_YOUTH = 'AY_YOUTH',
  MUSIC_CHOIR = 'MUSIC_CHOIR',
  DEACONRY = 'DEACONRY',
  ELDERSHIP = 'ELDERSHIP',
  HEALTH_MINISTRIES = 'HEALTH_MINISTRIES',
  LITERATURE_EVANGELISM = 'LITERATURE_EVANGELISM',
  MEDIA_TECH = 'MEDIA_TECH',
}

export enum PhotoPrivacy {
  PUBLIC_TO_ALL = 'PUBLIC_TO_ALL',
  VERIFIED_MEMBERS_ONLY = 'VERIFIED_MEMBERS_ONLY',
  REQUEST_APPROVAL_ONLY = 'REQUEST_APPROVAL_ONLY',
}

export enum InterestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  CANCELLED = 'CANCELLED',
  BLOCKED = 'BLOCKED',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  SUBMITTED_PENDING_PASTOR = 'SUBMITTED_PENDING_PASTOR',
  PASTOR_ENDORSED = 'PASTOR_ENDORSED',
  ADMIN_APPROVED = 'ADMIN_APPROVED',
  REJECTED = 'REJECTED',
}

export enum EducationLevel {
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  DIPLOMA = 'DIPLOMA',
  BACHELORS = 'BACHELORS',
  MASTERS = 'MASTERS',
  DOCTORATE = 'DOCTORATE',
  OTHER = 'OTHER',
}

export enum RelocationPreference {
  WILLING_TO_RELOCATE_ANYWHERE = 'WILLING_TO_RELOCATE_ANYWHERE',
  WITHIN_COUNTRY = 'WITHIN_COUNTRY',
  WITHIN_DIVISION = 'WITHIN_DIVISION',
  NOT_WILLING_TO_RELOCATE = 'NOT_WILLING_TO_RELOCATE',
}
